language: objective-c
osx_image: xcode61
rvm:
- 2.1.2
install:
- chmod u+x ./Travis/installUnity.sh
- ./Travis/installUnity.sh
script:
- chmod u+x ./Travis/installSDK.sh
- ./Travis/installSDK.sh
- openssl aes-256-cbc -K $encrypted_984f19857b4c_key -iv $encrypted_984f19857b4c_iv -in Config.json.enc -out Travis/UnityTestProject/Assets/StreamingAssets/Config.json -d
- chmod u+x ./Travis/runUnitTests.sh
- ./Travis/runUnitTests.sh
- chmod u+x ./Travis/build.sh
- ./Travis/build.sh
